language: python

branches:
  only:
    - py3unittest

python:
  - "2.7"
  - "3.4"

# command to install dependencies
install: "pip install -r requirements.txt"

services:
      - mysql

before_script:
  - mysql -e 'create database lychee; grant all on lychee.* to \'lychee\'@\'localhost\' identified by \'lychee\';'

# command to run tests
script: make test
