language: python

branches:
  only:
    - py3unittest

python:
  - "2.7"
  - "3.4"

# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip freeze

services:
    - mysql

before_install:
    - sudo apt-get install python-dev python3-dev

before_script:
  - mysql -u root -e 'create database lychee DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -u root  -e "create user 'lychee'@'localhost' IDENTIFIED BY 'lychee';"
  - mysql -u root -e "GRANT ALL ON lychee.* TO 'lychee'@'localhost';"

# command to run tests
script: make test
